# Generated by Django 4.1.6 on 2023-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_licence',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
