# Generated by Django 4.0.6 on 2023-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0004_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.CharField(default='', max_length=255),
        ),
    ]
