# Generated by Django 4.0.6 on 2023-06-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0005_driver_latitude_driver_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='islogged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='otp',
            field=models.CharField(default='', max_length=15),
        ),
    ]
