# Generated by Django 4.0.6 on 2023-07-01 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo_driver_app', '0006_driver_islogged_driver_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike')], max_length=10)),
                ('color', models.CharField(default='', max_length=100)),
                ('vehicle_number', models.CharField(default='', max_length=255)),
                ('image', models.FileField(default='', upload_to='vehicle/')),
                ('driver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.driver')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
