# Generated by Django 4.0.6 on 2023-07-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0010_alter_vehicletype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
