# Generated by Django 4.0.6 on 2023-07-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0011_alter_vehicletype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='country_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
