# Generated by Django 4.0.6 on 2023-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0014_alter_driver_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fcm_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
