# Generated by Django 4.0.6 on 2023-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0015_driver_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='', max_length=120),
        ),
    ]
