# Generated by Django 4.0.6 on 2023-08-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
        ('cargo_driver_app', '0016_alter_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='color.color'),
        ),
    ]
