# Generated by Django 4.0.6 on 2023-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0017_alter_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='title_ar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
