# Generated by Django 4.0.6 on 2023-09-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0018_vehicletype_title_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='city_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='name_ar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
