# Generated by Django 4.0.6 on 2023-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0019_driver_address_ar_driver_city_ar_driver_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='supplier_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
