# Generated by Django 4.0.6 on 2024-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0020_driver_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='session_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='token_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
