# Generated by Django 4.0.6 on 2024-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0021_driver_session_token_driver_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='civil_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
