# Generated by Django 4.0.6 on 2024-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0022_driver_civil_id_alter_driver_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
