# Generated by Django 4.0.6 on 2024-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0024_remove_driver_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
