BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
  XXXX XXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXXXXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX
          XXXXXXXXXX XXXXX XXX
        XXXXXXXXXX XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXX

    XXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
         
          
        XXXXXX
        XXXX XXXXX XXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXX

  XXXX XXXXXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXXX XXXXXXX XXXX XXXX XXX
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXX

  BBBBBBBB BBBBBBB