BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX  XXXXXXXXXXXXX
            XXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                
                BBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                 
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXX XXX XXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXX XXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXX
   
 
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
           
            XXXXXXXXXXXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
           
            
            XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
            X
                XXX XX X XXX XXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXX XXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XX
                    XXXXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXX
                      XX XXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXXX 
                      X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      X XXXX XXXXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX
                      X
                      
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   X
                XXX
            X

        XX
    XX
XXXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX

BBBBBBBB BBBBBBB