BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX
      XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXX

    XXXX XXXXXX XXXXX XXXXXX XXXX XXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXX XXXX XXXXXXX XXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXX XXXXX XXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXXXXXXXXX XXXXXXXXX X XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXXXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXXXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXX XXXXXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXX XXX XXXXXXXXXX XXX XXXXX XXXXXX XXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
    XXXX XXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX

  XXXXXXX
    XXXXXXXXXXXXX X
      XXXXXXXXX XXXXX XXXXXXXXXXX
    X
  XXXXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXX XXXXXX XXXXX XXX
        XXX XXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXXXXXXXXXXX
              XXX XXXXXXXXXX XXXXXXXXXXXX
            XXXXX
          XXXXX
           #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

        XXXXX

        XXXX XXXXX XXXXXX XXXXX XXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXX XXXXXX XXX
          XXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                  XX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                      XXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXX
                    X
                      XX XXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXX
                      XXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                      XX XXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXXX
            XXXXXX
          XXXXX

          XXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXX
          XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
            XX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
            X
              XX XXXXXXXXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX
              X
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX
                XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
              X
                XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XXX XXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
              XXXX

              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX
                XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
              X
                XX XXXXXXXXXX XXXXXXX XXXXXXXXXX X XXX XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
              XXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX
                XXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXX XXXXXXXXXXXXXXXX
              X
            XXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXXXXXXXXXXX
            X
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX
              XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX
            X
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXXX
          XXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXX
          X
            XX
              XXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX
              XXXXXXXX
              XXXXXXXXXXXXX
            X
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX
          XXXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXX XXX
    XXXXXX
  XXXXXXX
XXXXXXX
