# Generated by Django 4.0.6 on 2023-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='title_ar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
