BBBB BBBBBB
BBBB BBBB
  XXXX XXXXX XXXXXX XXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX   
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
              XXX gettext(u'footer_content') XXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'useful_links') XXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'signup_as_courier') XXXXXXXXX
              XXXXX
            XXXXXX
          XXXXXX
          
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'social_links') XXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                XXXXXX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX 
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'all_reserved') XXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX
  XXXXXXXXX
  XXXXXX
  XXXX XXX XXXXXX XXXX XXX

  XXXX XXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXX XXXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXX XXXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXXXX XXX XX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXXXXXXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXXXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXX X XXXX
                  XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                XXXXXX
                  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXXXXX X XXXXX
                  XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                X
                
            XXX
        XXX
    XXX
XXXXXXXXX 

 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #





  XXXXXXX
  
  XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XX XXX XXXX XXXXXXXX XXX XXX
  XXXXXXX