BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XX XXX XXXX XXXXXXXX XXX XXX
XXXXXX
XXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXX XXX XXXXX X XXXX XXXX XXXXXX XXXX XXXXX XX XXX XXXXX XXX XXXXX XXXX XXXXXXX XXXX XXXX XXXXXXX XXXXX XXXX XXX
XXXXXXXXXXXX X XXXXXXX X XXXXXXXX XXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXX XXXXXXX XXXX XXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX XX
XXXX XXXXXXX XXX XXX
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX X
XXXX XXXXXX XXX XXX
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXX XXXXXXX XXX
XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXX XXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
    XX
XXXX XXXXX XXXX XXX XXXXXXXXXX XXX XXX XXXXXXX XX XXXXX XXXXXXXX XXX XXXXX XXXXXXX XXX
XXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXX XX XXX XXXX XXX XXXX XXX XXXXXXX XXX
XXXXXXX XX XX XXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
XXXXXXX
XXXXXXX
    XXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
  X
XXXXXXXX
XXXXXX
XXXX XXX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXX 
    XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX gettext(u'best_courier') XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXX XXXXXX XXX XXX 
    XXXX XXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX 
          XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XX XXXXXXBBB BBBXX XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXX
          XXXXXX
          XXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX 
            XXXXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX 
                XXXX XXXX XX XXXXXX XXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXBBB BBBXX gettext(u'home') XXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                      BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                      BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                      BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                     
                      BBB BBBB BB BBBBBBBBB
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXX
                      BBBBBB
                      
                    XXXXX
                  XXXXX
                XXXXX 
              XXXXXX
            XXXXXX
            XXXX XXXX XXXX XXXXXX 
            XXXX XXXX XXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX 
              XXXX XXXXXXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'signup_as_courier') XXXX XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXXXX XXXXXX XXXXXXXX 
    XXXX XXXXXX XXXX  XXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXX XXX XXXXXXXXXX X XXXX XXXX XX XX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXXXX XXXX XXXXX X XXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX
        XXXXX
      XXXXXX
    XXXXXX
   
  XXXXXXXXX
  XXXX XXX XXXX XXXXXX XXX 