BBBB BBBBBB
  XXXX XXXXX XXXXXX XXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
              XXXXX XXX XXX XXXXX XX XXX X XXXXXXX XX XXXXX XXXXX XXX XXXX XX XX XXXX XXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX XX XXX XXXXXX XX XXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXX
               XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXX XX XXX XXXXXXX XXXX XXX XXXX XXXXXX XX XXXXXX XXXX XXX XXXXXX XXXX XXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXX XXXXXXXX XX XXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX
  XXXXXXXXX
  XXXXXX
  XXXX XXX XXXXXX XXXX XXX

  XXXX XXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXX XXXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXX XXXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXXXX XXX XX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXXXXXXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXXXXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXXX XXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX 
  XXXX XXXXXX XX XXX 
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX
  
  XXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XX XXX XXXX XXXXXXXX XXX XXX
  XXXXXXX