XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXX XXXXXXXX XXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX
            XXXX 
                
            XXXXX
        XXXXXXXXX
        XXX
            FFFFFFFFF
        XXXX
    XXXXXX
    XXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXX XX XXX XXXX XXX

    XXXX XXXXXX XX XXXXXXXXX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXXX