XXXXXX
    XXXXXXXXXXXX X XXXXXXX X XXXXXXXX XXXXXXXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXX
    XXXXXXX
      XXXX X
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXX XX
        XXXXXXXXXXX XXXXXXXX 
      X
        XX X
          XXXXXX XXXXXXXX
          XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
          XXXXXXXXXXXX XXXX
          XXXXXXXXXX XXXXX
          XXXXXXXXXXXXXX XXXXX
        X
        X X
          XXXXXX XXXXXXXX
          XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXX XX
        X
      X X
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXX
      X
      XXXXX X
        XXXXXXXXXXX XXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX X XXX XXX XXXXXXXX
        XXXXXXXX XXXXXXXXXXXXX
        XXXXXXX X XXXXX
      X
      XXXXXXXXXX X
        XXXXXX XXXX XX XXX XXX XXXXXX XXX XXXXX XX XXXX XXXXXXXXXX XX
        XXXXXXXXXX XXXXX XX XXX XXX XXXXXX XXX XXXX XXXX XX XXXX XXXXXXXXXX XX
      X
    XXXXXXXX
    XXXXXX
      XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
        XXXXXXXXXXXXXXX 
        XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX
      XXXXXX
    XXXXXXX
XXXXXXX