XXXXXXXXX XXXXX
XXXXX XXXXXX FFFFFFFF FFFFFFFFF  FFFFFFFF FFFFXX

  B BBBBBBB BBBBBBBBB B

  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX

      B BBBBBBB BBBBBBBBBBBBBB B

      B BBBBBBB BBBBBBBBBBB B
      B BBBBBBB BBBBBBBBBBBB B

      

      B BBBBBBB BBBBBBBBBBB B
    XXXXXX

    BBBBBBB BBBBBBBBB B
  XXXXXXX
XXXXXXX
