# Generated by Django 4.0.6 on 2023-07-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractfile',
            table='contract_file',
        ),
    ]
