BBBBBBB BBBBBBBBBBBBBBBBBBB BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
          XXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX 

  XXXX XXXX XXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
               #

              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  
                  XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    BB BBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXXX BBBBBXXXXXXXXXX
                    BBBBBB
                    BBBB
                    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBB
                  XXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
              X
                XXXXXXX
                  XXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXXXXX XXXXXXX
                    XXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBB BB BBBB
                  XXX XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXX XXXXXXXX
                    XXXX XXXXXXXX
                    XXXXXXXXX 
                    XXXXXXXXX 
                    XXXXBB BBBBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBB XXXX BBBBBXXXXX
                    XXX XXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXX XX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXX XX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXX XX XXXXXXXXXXXXX
                      XXXXXXXXX
                    XXXXX
                    XXXX
                      XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXX XX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXX
                    XXXXX
                  XXXXX
                  BBBBBB

                XXXXXXXX
              XXXXXXXX
            XXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXX
          XXXXXX
          XXXX XXXXXX XXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXX
      XXXX XXXXX XXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX
  XXXX XXXXXXXXX XXX
XXXXXX

XXXXXXXX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXX
        XXXXXXXXXXX X
          X
            XXXXXXXX XXX XX XX XX XXXXXX XXXXX XXX
            XXXXXXXXXX XXXXX XX XXXX XX XXXXX XXX
          XX
        XX
      XX
      XXXXXXXXXX
      XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX
    XXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX
      XXX XX X XXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXX
          XXXXX XXX
          XXXXXXXXXXXX XXXXXX
          XXXXXXXXXXXX XXXXXX 
          XXXXXXXXX XXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXXX XXXXXXXXXXXXXX X
            XXX XXXX X XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX 
    X
  XXX 
  
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXX XX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXXXXX XXXXXXXXXX
        XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXXX XXXXXXXXXX
        XXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXX XXXX XXXXXXX
        XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XXX
XXXXXXXXX

XXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX
      X
        XXXXXX XXXX XXX XXXXXXXX
        XXXXX XXXX XXXX XX XXXXXX XXXX XXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXX
      XX
      XXXXXXXX XX X
        XXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          X
            XXX XXX
            XXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX
          XXXXXXXX XXXXXX XXXXXXX X
            XX XXXXXXXXX XX XXXXXXXXXX X
              XXXXXXXX X XXXXXXXXXXXXX
              XXXXXX
                XXXXXX XXXXXXXXXXX
                XXXXX XXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXX
              XXX
            X
          X
        XX
      X
    XX
  X
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXX
    XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
        XXX XXX
        XXXXXX XXXXXXXXX
        XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXX XXXXXX XXXXXXX X
        XX XXXXXXXXX XX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXX
          XXXXXX
            XXXXXX XXXXXXX XXXXXXXXXX
            XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXX
          XXX
        X
      X
    XX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBB
