BBBBBBB BBBBBBBBBBBBBBBBBBB BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX

  XXXX XXXX XXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXX XXXXX XXX XXX
            XXXX XXXXXXXXXXXXXX XXX XXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX
                XXXX
                   X BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB BBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXX BBBB BBBBBBBBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXBBBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXX
                  XXXXX X XXXX
                  XXXXX X XXXX
                  BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
                  XXXXXXXXXXX XX X XXXX
                  BBBBB
                XXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXX XXX
            XXXX XXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXX
                  XXXX
                    XXXXXXXXX XXXXXXX
                    XXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXX
                     #

                  XXXXX
                XXXXXXXX
                XXXXXXX
                  
                  XXX XXXXXXXXX
                    
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    
                    XXXXXXXXX
                    
                    XXX XXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXX XX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXX XX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXX XX XXXXXXXXXXXXX
                      XXXXXXXXX
                    XXXXX
                    
                  XXXXX
                  
                XXXXXXXX
              XXXXXXXX
            XXXXXX
          XXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXX
          XXXXXX
          XXXX XXXXXX XXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXX
      XXXX XXXXX XXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX
  XXXX XXXXXXXXX XXX
XXXXXX

XXXXXXXX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXX
        XXXXXXXXXXX X
          X
            XXXXXXXX XXX XX XX XX XXXXXX XXXXX XXX
            XXXXXXXXXX XXXXX XX XXXX XX XXXXX XXX
          XX
        XX
      XX
      XXXXXXXXXX
      XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBB
