BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXX
            XXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                
                BBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                   
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXXXXX  XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXXXXX  XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                      BB BBBBBBBBBB
                      XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX 
                      BBBB
                      XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                      BBBBB
                    XXXXXX
                  XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXX
  
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XX XXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
XXXXXXXXX   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXX X XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXXXXXXX
            X
                XXX XX  X XXX XXXXXXXXXXX
                XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXX XXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XX
                    XXXXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXX
                      XX XXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXXXXX 
                      X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                      X 
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   X
                XXX
            X

        XX
    XX
XXXXXXXXX
XXXXXXXX
  XXXXXXXXXX XX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXXX XXXXXXXXXX
        XXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

  XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX

BBBBBBBB BBBBBBB