# Generated by Django 4.0.6 on 2023-09-15 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('title1', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('experience_desc', models.CharField(default='', max_length=255)),
                ('experience_year', models.CharField(default='', max_length=255)),
                ('experience_title', models.CharField(default='', max_length=255)),
                ('image', models.FileField(default='', upload_to='banners')),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'About_us',
            },
        ),
    ]
