# Generated by Django 4.0.6 on 2023-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='description_ar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about_us',
            name='experience_desc_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='about_us',
            name='experience_title_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title1_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.FileField(default='', upload_to='about_us'),
        ),
    ]
