BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXX
  XXXX X
     XXXXXXX XXXXXX
     XXXXXX XXXXX
  X
  XXXX XXXXXXXXXXXXXXXX
      XXXXXXXX XXXXX
  X
  XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXX
      XXXXXXX X XXXXX
  X
  XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXX X XXXXX XXXXXXXXXXX
  X
  XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXXXX
XX XXXX XXXXXXX XXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX
XX XXXXXXXXX XXXX XXX XXXXX XXXX XXX XXXX XXX XXXXXXXX
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXX XXXXXXX
XXX XXXX
XXX XXXXXXX
XXX XXXXXXXXXXX
XXXXXXXX XXXXXXXXX X
    XXX XXXX
    XXX XXXX
    XXXXX XXXXXXXX X X XXXX XXXXXXXXX XXXX XXXXXXXX XX
    XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXXXXXX
        XXXXX XXX
    XXX

    XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXX
        XXXX XXXX
        XXXXXXXXXX XXXX
    XXX

    XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXX XXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XX X
                XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXX X X XXXX XXXX XXXX XXX XX

                XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXX X XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXX XXXXXXXXX XXXXXXX X
                    XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XX XXXXXXXXXXXX X
                            XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX
                        X
                    X
                XXX
            XX
            XX XX X
                XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXX
            X
        XX
    X XXXX X
        XXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXX X
        XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXX XXXXXXXX X XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXX XXXXXXXXX XXXXXXX X
            XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXXXXXXXXX X
                    XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                X
            X
        XXX
    XXX

  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXX XXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXX XX XXX XXXXXXXXXXXX XXXXXXX
  XX XX XXXX XXX XXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXX XXXXXX XXX XXX
  XX XXXXXX XXXXXX XX XXX XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
  XX XXX XXX XXXX XXXXXX XX XXXXXX XXXX XXX XXXX XXXXXXX X XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX
  
  XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXX
  XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
        XX XXXX XXXXXXX XXX XXXX XX X XXXXX XXXX XXX XXX XXXXXXXXX XXX
        XX XXXXXXX XXX XXXXX XXXX XX XXX XXXXX XXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXX XXXXXX XX X XXXXXXXXXX X XXXXX
        XXXXXXX
        X

        XX XX XXX XXXXX XXX X XXXXXXXXX XXXX XXXXXXX XX XX X XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XX XXX XXX XXXXXXX XX XXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX X X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXX
        XXXXXXXX XXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXX X
    XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXX   
      XXXXXXXXX XXXXXXXXX
      XXXX XXXX
    XXX
  X XXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
X

XXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX 
          XXXX XXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                
                BBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      BBB BBBBBBBB BB BBBBBBBBBB
                      XXXXXXX XXXXXXXXXXXXXXXXXX
                      BBBBBB
                    XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  
                  XXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    
                      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                          XXXXX
                              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
                              XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXX
                          XXXXXX
                      XXXXXX
                      XXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XX
                          XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXX
   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XX XXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
XXXXXXXXX   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXX X XXXXXXXXXXXXXXXXX
            XXX XXXXX X XXXXXXXXXXXXXXXXXX
            XXX XXXXX X XXXXXXXXXXXXXXXXXX
            XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXXXXXXX
            X 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
              XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            
            XXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXX
            X
                XXX XX X XXX XXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXX XXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XX
                    XXXXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXX
                      XX XXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXXX 
                      X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      X 
                      XXXX XXXXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXX XXXXXXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                      X
                      XXXX XXXXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXX XXXXXXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                      X
                      XXXX XXXXXXXX XX XXXXX XX XXXXXXXXX XX XXXXX XXXXXXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                      X
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   X
                XXX
            X

        XX
    XX
XXXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX

BBBBBBBB BBBBBBB