BBBB BBBBBBBBBBB
    XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
    BB BBBBBBBBBBBB BB B
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXX
              XXXXXXX
                XXXX
                  XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXX
              XXXXXXXX
              XXXXXXX
                BBB BBBBBB BB BBBBB
                XXXX
                  XXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                      BBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                      BBBBB
                      
                      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXXXX
                        
                      XXXXXX
                    XXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX
  
                      XXXXXX  XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XX
  
                      XXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX
                    XXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
                      XXXX
                    XXXXXX
                  XXXXX
                XXXXX
                BBBBBB
              XXXXXXXX
            XXXXXXXX
          XXXXXX
          XXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXX
  
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX X
                        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        
                    
                        XXXXXX
                    XXXXXX
              XXXXXX
  
            XXXXXX
          XXXXXX
        XXXXXX
      BBBB
      XXXXXXXX XX XXXXXXXXXX
      BBBBB
      XXXXXX