# Generated by Django 4.0.6 on 2023-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=20)),
                ('weight_range', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
