# Generated by Django 4.0.6 on 2023-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0004_remove_pickuplocation_full_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike')], max_length=10)),
                ('color', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
            ],
        ),
    ]
