# Generated by Django 4.0.6 on 2023-06-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0006_user_is_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'service_time',
            },
        ),
    ]
