# Generated by Django 4.0.6 on 2023-06-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0007_service_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Time',
            new_name='Services_Time',
        ),
        migrations.AlterModelTable(
            name='services_time',
            table='services_time',
        ),
    ]
