# Generated by Django 4.0.6 on 2023-06-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0008_rename_service_time_services_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'time_slot',
            },
        ),
    ]
