# Generated by Django 4.0.6 on 2023-06-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0009_time_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services_Time',
        ),
    ]
