# Generated by Django 4.0.6 on 2023-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0010_delete_services_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.FileField(default='', upload_to='vehicle/'),
        ),
    ]
