# Generated by Django 4.0.6 on 2023-06-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0011_vehicle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='color',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_number',
        ),
    ]
