# Generated by Django 4.0.6 on 2023-06-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0013_vehicle_color_vehicle_vehicle_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='title',
        ),
    ]
