# Generated by Django 4.0.6 on 2023-07-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0014_remove_vehicle_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
