# Generated by Django 4.0.6 on 2023-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0015_delete_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuplocation',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
