# Generated by Django 4.0.6 on 2023-07-03 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0016_alter_pickuplocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
