# Generated by Django 4.0.6 on 2023-07-07 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0018_pickuplocation_is_default_pickuplocation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.CharField(max_length=120)),
                ('pickup_address', models.CharField(max_length=250)),
                ('pickup_latitude', models.CharField(max_length=50)),
                ('pickup_longitude', models.CharField(max_length=50)),
                ('destination_address', models.CharField(max_length=250)),
                ('destination_latitude', models.CharField(max_length=50)),
                ('destination_longitude', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.cargo_package')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
