# Generated by Django 4.0.6 on 2023-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0019_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
