# Generated by Django 4.0.6 on 2023-07-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0022_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documents',
            field=models.FileField(default='', upload_to='documents'),
        ),
    ]
