# Generated by Django 4.0.6 on 2023-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0023_user_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo_package',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
