# Generated by Django 4.0.6 on 2023-07-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0024_cargo_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_file',
            field=models.FileField(default='', upload_to='courier_documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='courier_certificate',
            field=models.FileField(default='', upload_to='courier_documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='courier_file1',
            field=models.FileField(default='', upload_to='courier_documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='courier_file2',
            field=models.FileField(default='', upload_to='courier_documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='courier_file3',
            field=models.FileField(default='', upload_to='courier_documents'),
        ),
    ]
