# Generated by Django 4.0.6 on 2023-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0027_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='documents',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='', upload_to='profile_pic'),
        ),
    ]
