# Generated by Django 4.0.6 on 2023-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0028_remove_user_documents_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo_package',
            name='order',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
