# Generated by Django 4.0.6 on 2023-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0030_alter_cargo_package_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo_package',
            name='size_ar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cargo_package',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
