# Generated by Django 4.0.6 on 2023-09-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0031_cargo_package_size_ar_alter_cargo_package_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courier_file4',
            field=models.FileField(default='', upload_to='courier_documents'),
        ),
    ]
