# Generated by Django 4.0.6 on 2023-09-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0032_user_courier_file4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='courier_certificate',
            new_name='commercial_license',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='courier_file1',
            new_name='commercial_register',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='courier_file2',
            new_name='manager_civil_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='courier_file3',
            new_name='owners_civil_ids',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='courier_file4',
            new_name='signature_auth',
        ),
    ]
