# Generated by Django 4.0.6 on 2023-09-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0033_rename_courier_certificate_user_commercial_license_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='commercial_license',
            new_name='courier_certificate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='commercial_register',
            new_name='courier_file1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='manager_civil_id',
            new_name='courier_file2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='owners_civil_ids',
            new_name='courier_file3',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='signature_auth',
            new_name='owners_civil_id',
        ),
    ]
