# Generated by Django 4.0.6 on 2023-11-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0034_rename_commercial_license_user_courier_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
