# Generated by Django 4.0.6 on 2024-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0035_user_otp_user_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
