# Generated by Django 4.0.6 on 2024-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0036_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
