# Generated by Django 4.2.2 on 2024-04-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0037_user_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
