# Generated by Django 4.2.2 on 2024-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0038_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
