# Generated by Django 4.2.2 on 2024-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0042_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='address_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
