# Generated by Django 4.2 on 2024-07-23 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0043_pickuplocation_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_otp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 7, 33, 57, 83680, tzinfo=datetime.timezone.utc)),
        ),
    ]
