# Generated by Django 4.0.6 on 2023-07-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0008_vehicle_status'),
        ('api', '0002_orders_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.driver'),
        ),
    ]
