# Generated by Django 4.0.6 on 2023-07-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0022_delete_order'),
        ('api', '0004_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='destination_apartment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='destination_area_street_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='destination_floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='destination_house_building',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pickup_address_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.pickuplocation'),
        ),
    ]
