# Generated by Django 4.0.6 on 2023-07-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orders_destination_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pickup_address_id',
        ),
    ]
