# Generated by Django 4.0.6 on 2023-07-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0022_delete_order'),
        ('api', '0006_remove_orders_pickup_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.pickuplocation'),
        ),
    ]
