# Generated by Django 4.0.6 on 2023-07-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orders_pickup_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pickup_id',
            new_name='pickup',
        ),
    ]
