# Generated by Django 4.0.6 on 2023-07-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0011_alter_vehicletype_status'),
        ('api', '0011_alter_orders_pickup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='vehicle_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.vehicletype'),
        ),
    ]
