# Generated by Django 4.0.6 on 2023-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_orders_pickup_date_alter_orders_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pickup_date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
