# Generated by Django 4.0.6 on 2023-07-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_orders_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pickup_date',
        ),
    ]
