# Generated by Django 4.0.6 on 2023-07-15 08:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0024_cargo_package_status'),
        ('cargo_driver_app', '0014_alter_driver_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=250)),
                ('pickup_time', models.CharField(default='', max_length=120)),
                ('pickup_address', models.CharField(blank=True, max_length=250)),
                ('pickup_latitude', models.CharField(blank=True, max_length=50)),
                ('pickup_longitude', models.CharField(blank=True, max_length=50)),
                ('destination_address', models.CharField(max_length=250)),
                ('destination_area_street_block', models.CharField(max_length=100, null=True)),
                ('destination_house_building', models.CharField(max_length=100, null=True)),
                ('destination_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_latitude', models.CharField(max_length=50)),
                ('destination_longitude', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.driver')),
                ('package', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.cargo_package')),
                ('pickup', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.pickuplocation')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.vehicletype')),
            ],
            options={
                'db_table': 'driver_orders',
            },
        ),
    ]
