# Generated by Django 4.0.6 on 2023-07-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_driverorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='orders',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.orders'),
        ),
    ]
