# Generated by Django 4.0.6 on 2023-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_driverorders_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverorders',
            name='orders',
        ),
        migrations.AddField(
            model_name='driverorders',
            name='order_unique_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
