# Generated by Django 4.0.6 on 2023-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_driverorders_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
