# Generated by Django 4.0.6 on 2023-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_orders_pickup_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_otp_verification',
            field=models.IntegerField(null=True),
        ),
    ]
