# Generated by Django 4.0.6 on 2023-07-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_orders_pickup_otp_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='pickup_otp_verification',
            field=models.IntegerField(null=True),
        ),
    ]
