# Generated by Django 4.0.6 on 2023-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_driverorders_pickup_otp_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pickup_mobile',
            new_name='destination_mobile',
        ),
        migrations.AddField(
            model_name='driverorders',
            name='country_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driverorders',
            name='destination_mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='orders',
            name='country_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
