# Generated by Django 4.0.6 on 2023-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_pickup_mobile_orders_destination_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
