# Generated by Django 4.0.6 on 2023-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_orders_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
