# Generated by Django 4.0.6 on 2023-07-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_driverorders_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorders',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
