# Generated by Django 4.0.6 on 2023-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_driverorders_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='device_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='driverorders',
            name='device_token',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='driverorders',
            name='fcm_token',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='device_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='device_token',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='fcm_token',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
