# Generated by Django 4.0.6 on 2023-07-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_driverorders_device_name_driverorders_device_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverorders',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='driverorders',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='fcm_token',
        ),
    ]
