# Generated by Django 4.0.6 on 2023-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_driverorders_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='company_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='orders',
            name='company_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
