# Generated by Django 4.0.6 on 2023-09-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_driverorders_company_id_orders_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='paymentId',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='driverorders',
            name='paymentMethod',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driverorders',
            name='paymentStatus',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentId',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='paymentStatus',
            field=models.CharField(default='', max_length=150),
        ),
    ]
