# Generated by Django 4.0.6 on 2023-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_driverorders_paymentid_driverorders_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorders',
            name='paymentId',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='driverorders',
            name='paymentMethod',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='driverorders',
            name='paymentStatus',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentId',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentStatus',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
