# Generated by Django 4.2.2 on 2024-04-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_user_app', '0037_user_token_version'),
        ('api', '0036_driverorders_order_by_orders_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorders',
            name='package',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.cargo_package'),
        ),
        migrations.AlterField(
            model_name='driverorders',
            name='pickup',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.pickuplocation'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='package',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.cargo_package'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pickup',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_user_app.pickuplocation'),
        ),
    ]
