# Generated by Django 4.2.2 on 2024-04-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_driver_app', '0025_alter_driver_email'),
        ('api', '0037_alter_driverorders_package_alter_driverorders_pickup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorders',
            name='vehicle_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.vehicletype'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='vehicle_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_driver_app.vehicletype'),
        ),
    ]
