# Generated by Django 4.2.2 on 2024-04-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_trackorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorders',
            name='order_by',
            field=models.IntegerField(default=1),
        ),
    ]
