# Generated by Django 4.2.2 on 2024-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_driverorders_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_by',
            field=models.IntegerField(default=1),
        ),
    ]
