# Generated by Django 4.0.6 on 2024-01-23 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('address', models.TextField(default='', max_length=255)),
                ('whatsapp_url', models.CharField(default='', max_length=255)),
                ('instagram_url', models.CharField(default='', max_length=255)),
                ('facebook_url', models.CharField(default='', max_length=255)),
                ('youtube_url', models.CharField(default='', max_length=255)),
                ('twitter_url', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support',
            },
        ),
    ]
