# Generated by Django 4.0.6 on 2024-01-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
