# Generated by Django 4.0.6 on 2024-01-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_support_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='facebook_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='support',
            name='instagram_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='support',
            name='twitter_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='support',
            name='whatsapp_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='support',
            name='youtube_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
