# Generated by Django 4.0.6 on 2024-01-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_support_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='support',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='support',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='support',
            name='whatsapp_url',
        ),
        migrations.RemoveField(
            model_name='support',
            name='youtube_url',
        ),
    ]
