XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XX XXXXXX FFFFFFFF FFFFFFFFFFFFX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXX FFFFFFFF FFFFFFFFFFFFX XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXX FFFFFFFF FFFFFFFFFFFFX XXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
  XXXX
  XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
       BBB BBBB BB BBBBBBBBBBBBBBB B
          B BBBBBB BBBBBBBBBBBBBB B BBBBBBB B
          B BBB BBBBBBB BB BBBBBBBBBBBBB B
            B BBBBBB BBBBBBBBBBB B BBB B BBBBBBB BBBBBBBBBBB B
            B BB BBBBBBBBBBB BB BBBBBBBB B
              B BBBBBB BBBBBBBBBBBBBB B BBBBBB B
            B BBBBB B
          B BBBBBB

          XXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBB BB BBBBBB XXXXXXXXXBBBBBXX
            BB BBBBBBBB BB BBBBBBBBBBBB B
              B BBBBBB BBBBBBBB B BBB B
            B BBBB B
              B BBBBBB BBBBBBBB B BBB B BBBBBBB BBBBBBBB B
            B BBBBB

            XX XXXXXXBB BBBBBBBB FFFFFFFF FFF  FFFFFFFF FFFFFFFFFFFFBBBBXBBBBBX XXXXXXXXXXXXXXXBB BBBBBBBB BB BBBBBBBB XXXXXXBBBBBBB BBBBBBBBBBBBBB BB BBBBBB XXXXXXBBBBBXX
              XX XXXXXXXXXXXXXXX XXXXXX
              XXX
                
                BB BBBBBBBBBBBBBXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXBBBBB
              XXXX
            XXXX

            BB BBBBBBBBBBBBB B
              XXX XXXXXXXXXX XXXXXXXXXXXXXX
              BBB BBBBBBB BB BBBBBBBBBBBBB B
                B BBBBBB BBBBBBBBBBB B BBB B BBBBBBB BBBBBBBBBBB B
                XXX XXXXXXXXXXXXXXXXX
                  XX XXXXXX FFFFFFFF FFF  FFFFFFFF FFFFFFFFFFFFX XXXXXXXXXXXXXXXBB BBBBBBBBBBB BB BBBBBBBB XXXXXXBBBBBXX
                    XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXX
                  XXXX
                XXXXX
              B BBBBBB
              XXXXX
            B BBBBB
          XXXXX
       BBBBBB
      XXXXX
    XXXXXX
  XXXXXX
XXXXXXXX
