# Generated by Django 4.0.6 on 2024-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paymentId',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paymentStatus',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
