# Generated by Django 4.0.6 on 2024-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_paymentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
