BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                
                BBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                  
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXX
   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XX XXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
XXXXXXXXX   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXX X XXXXXXXXXXXXXXXXX
          XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX

          XXXXXXXXXXXX
          X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX
          X
          
          XXXXXXXXXXXXXXXXXX
          X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          X
         
          
          XXXXXXXXXXX XX XXXXXXXXXXXXXXX
          X
                XXX XX X XXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXX XXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XX
                    XXXXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXX 
                      XX XXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXXXXX 
                      X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                      X XXXX XXXXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX
                      X
                      
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   X
                XXX
            X

        XX
    XX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
  X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXX XXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX

BBBBBBBB BBBBBBB