BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX 
            XXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
            XXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX

    XXXX XXXX XXXXXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                
                BBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                  
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX 
                        BBBB
                        XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                        BBBBB
                    XXXXXX
                  XXXXXX
                  
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXX
  XXXXXX
   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XX XXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
XXXXXXXXX   
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXX
        XXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXX X XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXX
            X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
            X
           
            XXXXXXXXXXXXX
            X
                XXX XX X XXX XXXXXXXXXXX
                XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXX XXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XX
                    XXXXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXX 
                      XX XXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXXXXX 
                      X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      X XXXX XXXXXXXX XX XXXXX XX XXXXXXXXX XX XXXXXXXX XXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX
                      X
                      
                    XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   X
                XXX
            X

        XX
    XX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    X
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX

BBBBBBBB BBBBBBB