BBBBBBB BBBBBBBBBBBBBBBBBBB BBBBB BBBBBBB
XXXXXXX
  XXXXXXXXXXX X
    XXXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXX XXX XXXX
    XXXXXXX XXXXXXXX
X
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
          XXXXX 
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX

  XXXX XXXX XXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
              X
                XXXXXXX
                  XXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXXXX XXXXXXXXX
                    XXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBB BB BBBB
                  XXX XXXXXXXXX
                    XXXXXXXXX
                    
                    XXXXXXXXX
                    XXXXXXXXX
                    
                    XXXX
                      XXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX
                      X
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX BB BBBBBBBBBBB BB B XXXXXXXX BBBBBXXXXXXXXXXXXXXX
                      XXXXXXXXX
                    XXXXX
                    XXXX
                      XX
                        XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXXX XXXXXXX
                        XXX XXXXXXXXXX XXXXXXXXXXXX
                      XXXXX
                      XX
                        XXXXXXXXXX XXXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                      XXXXX
                    XXXXX
                  XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX
            XXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXX
          XXXXXX
          XXXX XXXXXX XXX
        XXXXXX
        XXXX XXXXX XXX
      XXXXXX
      XXXX XXXXX XXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXX
  XXXX XXXXXXXXX XXX
XXXXXX

XXXXXXXX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXX
        XXXXXXXXXXX X
          X
            XXXXXXXX XXX XX XX XX XXXXXX XXXXX XXX
            XXXXXXXXXX XXXXX XX XXXX XX XXXXX XXX
          XX
        XX
      XX
      XXXXXXXXXX
      XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXX XXXX X XXX
    XXXX XX XXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
     #
 #
 #

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXX XX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXXXXX XXXXXXXXXX
        XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXXX XXXXXXXXXX
        XXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXX
        XXXXXX XXXX XXXX XXXXXXX
        XXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XXX
XXXXXXXXX

XXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX
      X
        XXXXXX XXXX XXX XXXXXXXX
        XXXXX XXXX XXXX XX XXXXXX XXXX XXXXXXXXX
        XXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXX
      XX
      XXXXXXXX XX X
        XXXXXXX
          XXXXXXXXXXXXXXXXXXXXX
          X
            XXX XXX
            
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX
          XXXXXXXX XXXXXX XXXXXXX X
            XX XXXXXXXXX XX XXXXXXXXXX X
              XXXXXXXX X XXXXXXXXXXXXX
              XXXXXX
                XXXXXX XXXXXXXXXXX
                XXXXX XXXXXXX XXX XXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXX
              XXX
            X
          X
        XX
      X
    XX
  X
XXXXXXXXX

XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXX XX X XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXX
    XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
        XXX XXX
        XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXX XXXXXX XXXXXXX X
        XX XXXXXXXXX XX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXX
          XXXXXX
            XXXXXX XXXXXXX XXXXXXXXXX
            XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXX
          XXX
        X
      X
    XX
  XXX
XXXXXXXXX
BBBBBBBB BBBBBBB
